# Generated by Django 5.1.4 on 2026-09-13 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. The Wedding of Sarah & Alex', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug for the invitation', max_length=150, unique=True)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday Celebration'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('corporate', 'Corporate Event / Gathering'), ('graduation', 'Graduation'), ('general', 'Celebration / Party')], default='wedding', max_length=30)),
                ('hosts_or_celebrants', models.CharField(help_text='Couple names, birthday person, or host organization (e.g. Sarah & Alex)', max_length=255)),
                ('event_date', models.DateTimeField(help_text='Main date and time of the event')),
                ('venue_summary', models.CharField(blank=True, help_text='Short venue & city name (e.g. The Glasshouse, Bali)', max_length=255)),
                ('cover_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80', help_text='Direct image URL for cover banner & OpenGraph preview')),
                ('audio_url', models.URLField(blank=True, help_text='Optional direct MP3 URL for background music')),
                ('welcome_quote', models.TextField(blank=True, default='Together with our families, we warmly invite you to celebrate this special day with us.')),
                ('theme_color', models.CharField(default='#b45309', help_text='Accent color hex code (e.g. #b45309, #4f46e5, #be185d)', max_length=30)),
                ('font_family', models.CharField(choices=[('serif', 'Classic Elegant Serif (Playfair Display)'), ('sans', 'Modern Clean Sans (Plus Jakarta Sans)'), ('cormorant', 'Timeless Romance (Cormorant Garamond)')], default='serif', max_length=30)),
                ('gift_bank_name', models.CharField(blank=True, help_text='Bank or digital wallet name', max_length=100)),
                ('gift_account_number', models.CharField(blank=True, help_text='Account/Phone number', max_length=100)),
                ('gift_account_name', models.CharField(blank=True, help_text='Account holder name', max_length=150)),
                ('gift_note', models.TextField(blank=True, default='Your presence and prayers mean the world to us. For those who asked about gifts, a digital envelope is available below.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('max_pax', models.PositiveIntegerField(default=2, help_text='Max guest allocation')),
                ('is_attending', models.BooleanField(blank=True, help_text='Null=Pending, True=Attending, False=Declined', null=True)),
                ('actual_pax', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitations.invitation')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('invitation', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Holy Matrimony, Reception, Dinner Party', max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('map_url', models.URLField(blank=True, help_text='Google Maps direction link')),
                ('dress_code', models.CharField(blank=True, help_text='e.g. Formal, Pastel, Smart Casual', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=120)),
                ('attendance_status', models.CharField(choices=[('attending', 'Attending'), ('maybe', 'Maybe'), ('declined', 'Cannot Attend')], default='attending', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes', to='invitations.guest')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='invitations.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
