# Generated by Django 5.1.4 on 2026-09-13 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload custom background song (MP3)', null=True, upload_to='invitations/audio/'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload custom cover photo (PNG/JPG)', null=True, upload_to='invitations/covers/'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Optional direct MP3 URL for background music (used if no file uploaded)'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='cover_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80', help_text='Direct image URL for cover banner & OpenGraph preview (used if no file uploaded)'),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='invitations/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional photo caption', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
