# Generated by Django 5.1.4 on 2026-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitation_audio_file_invitation_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
