# Generated by Django 5.1.4 on 2026-09-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_galleryphoto_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps direction link', max_length=500),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
