# Generated by Django 5.1.4 on 2026-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_schedule_map_url_alter_schedule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='cover_focus_position',
            field=models.CharField(blank=True, default='center', help_text="Focal point / ROI for cover photo (e.g. 'center', 'top', '50% 20%')", max_length=50),
        ),
    ]
