# Generated by Django 5.1.4 on 2026-09-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_invitation_cover_focus_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='cover_zoom_level',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Cover photo zoom percentage (100 = 1.0x, 150 = 1.5x, 200 = 2.0x)'),
        ),
    ]
