# Generated by Django 5.1.4 on 2026-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_invitation_cover_zoom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='theme_style',
            field=models.CharField(choices=[('classic', 'Classic Ivory & Stone (Warm & Timeless)'), ('dark', 'Midnight Luxe / Black Tie (Dramatic & Sleek)'), ('minimal', 'Pure Minimal White (Crisp & Clean)'), ('romantic', 'Blush Petal (Soft & Romantic)'), ('botanical', 'Botanical Garden (Lush & Natural)')], default='classic', help_text='Visual background and presentation theme', max_length=30),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='font_family',
            field=models.CharField(choices=[('serif', 'Classic Serif (Playfair Display)'), ('cormorant', 'Timeless Romance (Cormorant Garamond)'), ('cinzel', 'Regal Royal (Cinzel)'), ('greatvibes', 'Romantic Calligraphy (Great Vibes)'), ('lora', 'Poetic Literature (Lora)'), ('sans', 'Modern Clean (Plus Jakarta Sans)'), ('montserrat', 'Contemporary Editorial (Montserrat)')], default='serif', max_length=30),
        ),
    ]
