# Generated by Django 5.1 on 2026-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_alter_invitation_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='gallery_effect',
            field=models.CharField(blank=True, choices=[('grid', 'Classic Grid (Masonry)'), ('slide', 'Smooth Slide (Horizontal Scroll)'), ('carousel', 'Interactive Carousel (Slideshow)'), ('move', 'Continuous Move (Auto Marquee)'), ('fade', 'Cinematic Crossfade Deck')], default='grid', help_text='Visual layout and animation effect for the photo gallery', max_length=30),
        ),
    ]
