# Generated by Django 5.1 on 2026-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_invitation_gallery_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct image URL or Google Drive photo link', max_length=500),
        ),
        migrations.AddField(
            model_name='invitation',
            name='gallery_folder_url',
            field=models.URLField(blank=True, help_text='Public Google Drive folder link containing gallery photos', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invitations/gallery/'),
        ),
    ]
